[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
[services.variables]
PORT = "8080"
HOST = "0.0.0.0"
LANGCHAIN_TRACING_V2 = "true"
